# Generated by Django 3.0.1 on 2019-12-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191228_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterory',
            name='type_category',
            field=models.CharField(choices=[('Language', 'Programming Language'), ('Framework', 'Framework'), ('Library', 'Library')], default='Language', max_length=30),
        ),
    ]
