# Generated by Django 3.0.1 on 2019-12-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_caterory_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
