# Generated by Django 3.0.1 on 2019-12-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191228_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caterory',
            name='type_category',
        ),
        migrations.AlterField(
            model_name='caterory',
            name='name_category',
            field=models.CharField(choices=[('Language', 'Programming Language'), ('Framework', 'Framework'), ('Library', 'Library'), ('ML', 'Machine Learning'), ('Redes', 'Redes')], default='Language', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
