# Generated by Django 3.0.1 on 2019-12-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191230_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caterory',
            name='name_category',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
