# Generated by Django 3.0.1 on 2020-01-06 05:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191229_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.custom_upload_to),
        ),
    ]
