# Generated by Django 3.0.1 on 2019-12-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20191231_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
